# Generated by Django 5.0.7 on 2024-07-31 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "character",
                    models.CharField(
                        choices=[("user", "User"), ("byte-genie", "ByteGenie")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "chats",
            },
        ),
    ]
